### ISSUE TITLE
Add nearest neighbour matching to simulations for revision

### ISSUE THREAD

**Issue by Kertoo** [ncn-foreigners/paper-nonprob-pmm#2]

**Comment by BERENZ** [comment]
+ When the outcome model has only one covariate, do the proposed estimators perform similarly with \citet{yang2021}?
+ When the outcome model has multiple covariates (e.g. $X_1,...,X_p)$ and it is correctly specified, do the proposed estimators perform better than Yang et al (2021) in terms of bias reduction and/or efficiency?
+ When the outcome model is misspeicified (e.g., missing one of the covariates), do the proposed estimators yield larger bias compared to \citet{yang2021} as they use the outcome model twice for both matching and imputation?
